**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

Use the next code cell to fetch the dataset.

In [1]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [ ]:
# List tables in the dataset
tables = list(client.list_tables(dataset_ref))

# Print the table names and count
table_names = [table.table_id for table in tables]
num_tables = len(tables)

print(f"Tables in the 'chicago_crime' dataset: {table_names}")
print(f"Total number of tables: {num_tables}")

Tables in the 'chicago_crime' dataset: ['crime']
Total number of tables: 1

In [2]:
# Use SQL to list tables in the dataset
query = """
    SELECT table_name
    FROM `bigquery-public-data`.INFORMATION_SCHEMA.TABLES
    WHERE table_schema = 'chicago_crime'
"""

# Run the query
query_job = client.query(query, project="bigquery-public-data")
tables = query_job.result()

# Extract and print the table names
table_names = [table["table_name"] for table in tables]
num_tables = len(table_names)

print(f"Tables in the 'chicago_crime' dataset: {table_names}")
print(f"Total number of tables: {num_tables}")

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [3]:
# Use SQL to count columns with TIMESTAMP data in the crime table
query = """
    SELECT COUNT(column_name) as num_timestamp_fields
    FROM `bigquery-public-data`.INFORMATION_SCHEMA.COLUMNS
    WHERE table_name = 'crime' AND data_type = 'TIMESTAMP'
"""

# Run the query
query_job = client.query(query, project="bigquery-public-data")
result = query_job.result()

# Extract and print the number of columns with TIMESTAMP data
for row in result:
    num_timestamp_fields = row["num_timestamp_fields"]

print(f"Number of columns with TIMESTAMP data in the 'crime' table: {num_timestamp_fields}")

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [ ]:
fields_for_plotting = ['latitude', 'longitude']

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [ ]:
# Specify the table name (replace with the actual table name if different)
table_name = "crime"

# Construct a reference to the crime table
table_ref = dataset_ref.table(table_name)

# Get the schema of the crime table
table = client.get_table(table_ref)

# Use list_rows to inspect a few values
rows = client.list_rows(table, max_results=5)  # Adjust max_results as needed

# Display the selected columns for each row
for row in rows:
    print(f"Location: {row['location']}")
    print(f"Latitude: {row['latitude']}")
    print(f"Longitude: {row['longitude']}")
    print("------")

Location: (41.885729338, -87.625780935)
Latitude: 41.885729338
Longitude: -87.625780935
------
Location: (41.885112119, -87.624484053)
Latitude: 41.885112119
Longitude: -87.624484053
------
Location: (41.885191719, -87.624486846)
Latitude: 41.885191719
Longitude: -87.624486846
------
Location: (41.884484216, -87.629030004)
Latitude: 41.884484216
Longitude: -87.629030004
------
Location: (41.885729587, -87.625821329)
Latitude: 41.885729587
Longitude: -87.625821329
------

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*